namespace SqlServer.Metrics.Provider
{
    public enum BuilderTypes
    {
        AverageElapsedTimeMetricsBuilder,
        ExecutionCountMetricsBuilder,
        MaxElapsedTimeMetricsBuilder,
        MinElapsedTimeMetricsBuilder,
        LastElapsedTimeMetricsBuilder,
        MaxPhysicalReadsMetricsBuilder,
        MinPhysicalReadsMetricsBuilder,
        LastPhysicalReadsMetricsBuilder,
        AveragePhysicalRreadsMetricsBuilder,
        MaxLogicalReadsMetricsBuilder,
        MinLogicalReadsMetricsBuilder,
        LastLogicalReadsMetricsBuilder,
        AverageLogicalRreadsMetricsBuilder,
        MaxPageServerReadsMetricsBuilder,
        MinPageServerReadsMetricsBuilder,
        LastPageServerReadsMetricsBuilder,
        AveragePageServerReadsMetricsBuilder,
        MaxLogicalWritesMetricsBuilder,
        MinLogicalWritesMetricsBuilder,
        LastLogicalWritesMetricsBuilder,
        AverageLogicalWritesMetricsBuilder,
        MaxWorkerTimeMetricsBuilder,
        MinWorkerTimeMetricsBuilder,
        LastWorkerTimeMetricsBuilder,
        AverageWorkerTimeMetricsBuilder,
        MaxPageSpillsMetricsBuilder,
        MinPageSpillsMetricsBuilder,
        LastPageSpillsMetricsBuilder,
        AveragePageSpillsMetricsBuilder,
        EstimatedExecutionCountBuilder
    }
}